{
  removedPlugins ? [
    "DatabaseTools"
    "angular"
    # "c"
    # "cidr-clangd"
    # "cidr-compiler-custom"
    # "cidr-linkerscript"
    # "cidr-parallelStacks"
    # "clion"
    # "clion-compdb"
    # "clion-diagnostics"
    # "clion-embedded"
    # "clion-embedded-platformio"
    # "clion-makefile"
    # "clion-meson"
    # "clion-packageManager"
    # "clion-performanceTesting"
    # "clion-radler"
    # "clion-test-boost"
    # "clion-test-catch"
    # "clion-test-ctest"
    # "clion-test-doctest"
    # "clion-test-google"
    # "clion-west"
    "clouds-docker-gateway"
    "clouds-docker-impl"
    # "cmake"
    # "color-scheme-all_hallows_eve"
    # "color-scheme-blackboard"
    # "color-scheme-cobalt"
    # "color-scheme-dawn"
    # "color-scheme-espresso"
    # "color-scheme-github"
    # "color-scheme-monokai"
    # "color-scheme-rails_casts"
    # "color-scheme-solarized-cidr"
    # "color-scheme-twilight"
    # "color-scheme-vibrant_ink"
    # "color-scheme-warmNeon"
    # "color-scheme-xcode"
    # "completionMlRanking"
    # "completionMlRankingModels"
    # "configurationScript"
    # "copyright"
    "css-plugin"
    "cwm-plugin"
    # "dev"
    # "dts"
    "featuresTrainer"
    "fullLine"
    "gateway-plugin"
    "grazie"
    # "grid-plugin"
    "html-tools"
    "ini" # !I
    # "intellij-rust"
    "javascript-debugger"
    "javascript-intentions"
    "javascript-plugin"
    # "json"
    "jsonpath" # !I
    "karma"
    "keymap-eclipse"
    "keymap-netbeans"
    # "keymap-qtcreator"
    # "keymap-resharper"
    # "keymap-visualStudio"
    "keymap-xcode"
    "less"
    "localization-ja"
    "localization-ko"
    "localization-zh"
    # "makefile"
    # "markdown"
    "mcpserver"
    # "nativeDebug-plugin"
    "nextjs"
    "nodeJS"
    "nodeJS-remoteInterpreter"
    # "performanceTesting"
    # "performanceTesting-async"
    "platform-ijent-impl"
    # "platform-images"
    "postcss"
    "prettierJS"
    "python-ce" # TODO:
    # "qml-plugin"
    "qodana"
    # "qt-plugin"
    "react"
    "remote-dev-server"
    # "remoteRun"
    "restClient"
    "sass-plugin"
    # "searchEverywhereMl"
    # "serial-monitor"
    # "settingsSync"
    "sh-plugin" # !I
    "station-plugin"
    # "statsCollector"
    "styled-components"
    "stylelint"
    "tailwindcss"
    # "tasks"
    # "tasks-timeTracking"
    # "terminal"
    "textmate-plugin"
    "toml" # !I
    "tslint"
    "uml" # !I
    # "vcs-git"
    # "vcs-git-commit-modal"
    # "vcs-github"
    "vcs-gitlab"
    "vcs-hg"
    "vcs-perforce"
    "vcs-svn"
    "vitejs"
    "vuejs-plugin"
    "webComponents"
    "webDeployment"
    "webpack"
    "xpath" # !I
    "yaml" # !I

    "plugin-classpath.txt"
  ],
}:
true
